name: 🐛 Bug
description: Something doesn't seems right 🧐
title: "[BUG] "
labels: [bug]
assignees:
  - trbnhck
body:
  - type: markdown
    attributes:
      value: |
        Thank you for opening a bug report 🐛! To address this bug as fast as possible, there is some more information needed
  - type: input
    id: browser
    attributes:
      label: Browser
      description: Which browser were you using? Please provide the version as well 
      placeholder: Google Chrome Version 104.0.5112.79
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Bug description
      description: What happened? What should have happened?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: What needs to be done, to reproduce this bug?
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Everything else, what might be relevant for this bug report
    validations:
      required: true
  
    
